server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=dbBanHang;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jwt:
  signerKey: "baodeptrai16qTFQgn0y3Rw3U9oKO8Jn7gDxUi54jaB4mVGRwh1pkY7CQaDfgYfB"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
